### PR TITLE
Version controlling GLOSSARY

### PR DESCRIPTION
**Pull request by halian-vilela**
Bringing the GLOSSARY to the repo, as discussed in #14

### CODE REVIEW

**Comment by cezaraugusto** [comment]
I think this is cool but not sure how it is connected with #14. this seems more like a style guide for authoring docs and not really translating them. am I missing something?

**Comment by halian-vilela** [comment]
> I think this is cool but not sure how it is connected with #14. this seems more like a style guide for authoring docs and not really translating them. am I missing something?

Hey @cezaraugusto 

I think the main purpose of this file is let people add their own entries to the glossary and keep discussions about specific terms in the pull requests instead of the little glossary with limited access that lives in #4 now.

For example, in my revisions yesterday I've stumbled upon some terms that I'm pretty sure will have at least 2-3 variations throughout the translation project.

I guess that every time someone finds such terms, they should add it to the glossary and then we try to find a standard term.

**Comment by gmsecrieru** [comment]
Thanks for your help but I believe most of this does not relate to the translation/project. 

All MD documents are well structured with examples and following a proper code style. Our goal is to provide a proper PT-BR translation without changing structure, code examples etc.

**Comment by halian-vilela** [comment]
@cezaraugusto @gmsecrieru 

Sorry guys!! This PR came with the wrong text!! The file that went here was the previous version, a wrong copy and paste... 

What I wanted to PR was this: https://github.com/halian-vilela/pt-BR.reactjs.glossary

As I stated [here](https://github.com/reactjs/pt-BR.reactjs.org/issues/14#issuecomment-462037973) I initially thought that we couldn't add `.md` files, but then the guys suggested that I should add this one to the repo.

Should I make another PR correcting the text? 

I personally think that this structure is better for adding new terms under their own letters.

What do you think?

**Comment by fjoshuajr** [comment]
> @cezaraugusto @gmsecrieru
> 
> Sorry guys!! This PR came with the wrong text!! The file that went here was the previous version, a wrong copy and paste...
> 
> What I wanted to PR was this: [halian-vilela/pt-BR.reactjs.glossary](https://github.com/halian-vilela/pt-BR.reactjs.glossary)
> 
> As I stated [here](https://github.com/reactjs/pt-BR.reactjs.org/issues/14#issuecomment-462037973) I initially thought that we couldn't add `.md` files, but then the guys suggested that I should add this one to the repo.
> 
> I've made some corrections to the text.
> 
> I personally think that this structure is better for adding new terms under their own letters.
> 
> What do you think?

Glad you fixed the content 👍

But @gmsecrieru has already created a PR (#46) addressing the glossary issue.

@halian-vilela would you mind submitting your changes there?

I'm closing this in favor of #46, just to avoid two PRs addressing the same issue.

**Comment by halian-vilela** [comment]
> > @cezaraugusto @gmsecrieru
> > Sorry guys!! This PR came with the wrong text!! The file that went here was the previous version, a wrong copy and paste...
> > What I wanted to PR was this: [halian-vilela/pt-BR.reactjs.glossary](https://github.com/halian-vilela/pt-BR.reactjs.glossary)
> > As I stated [here](https://github.com/reactjs/pt-BR.reactjs.org/issues/14#issuecomment-462037973) I initially thought that we couldn't add `.md` files, but then the guys suggested that I should add this one to the repo.
> > I've made some corrections to the text.
> > I personally think that this structure is better for adding new terms under their own letters.
> > What do you think?
> 
> Glad you fixed the content 👍
> 
> But @gmsecrieru has already created a PR (#46) addressing the glossary issue.
> 
> @halian-vilela would you mind submitting your changes there?
> 
> I'm closing this in favor of #46, just to avoid two PRs addressing the same issue.

Hey @fjoshuajr 

The text is too big to the GitHub interface, are there a better way to change that file? How could I change it locally and push ?

**Pull request closed without merging**
